# Generated by Django 5.0.4 on 2024-05-21 07:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='resumes/'),
        ),
    ]
