# Generated by Django 5.0.4 on 2024-05-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passenger',
            field=models.IntegerField(),
        ),
    ]
