# Generated by Django 5.0.4 on 2024-05-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passenger_passenger_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='fisrt_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
