# Generated by Django 5.0.4 on 2024-05-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(blank=True, to='flights.passenger'),
        ),
    ]
