# Generated by Django 5.0.4 on 2024-05-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_booking_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='infants',
        ),
    ]
