# Generated by Django 5.0.4 on 2024-05-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_remove_booking_adults_remove_booking_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
