# Generated by Django 5.0.4 on 2024-05-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('airport_staff', 'Airport Staff'), ('customer', 'Customer')], default='user', max_length=50),
            preserve_default=False,
        ),
    ]
