# Generated by Django 5.0.4 on 2024-05-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('airport_staff', 'Airport Staff'), ('customer', 'Customer')], max_length=50, verbose_name='role'),
        ),
    ]
